Repository OCA/currency, pull requests merged in 2019-05, with the labels that each got.

#51 [12.0][ADD] currency_rate_update_oxr: OpenExchangeRates.org provider
  currency_rate_update_oxr/README.rst
  currency_rate_update_oxr/__init__.py
  currency_rate_update_oxr/__manifest__.py
  currency_rate_update_oxr/models/__init__.py
  currency_rate_update_oxr/models/res_company.py
  currency_rate_update_oxr/models/res_config_settings.py
  currency_rate_update_oxr/models/res_currency_rate_provider_OXR.py
  currency_rate_update_oxr/readme/CONFIGURE.rst
  currency_rate_update_oxr/readme/CONTRIBUTORS.rst
  currency_rate_update_oxr/readme/DESCRIPTION.rst
  currency_rate_update_oxr/static/description/icon.png
  currency_rate_update_oxr/static/description/index.html
  currency_rate_update_oxr/tests/__init__.py
  currency_rate_update_oxr/tests/test_currency_rate_update_oxr.py
  currency_rate_update_oxr/views/res_config_settings.xml
Labels: approved, ready to merge

#53 [12.0][IMP] currency_rate_update: use last_successful_run
  currency_rate_update/__manifest__.py
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/tests/test_currency_rate_update.py
  currency_rate_update/views/res_currency_rate_provider.xml
Labels: approved

#41 [12.0][MIG] currency_rate_inverted
  currency_rate_inverted/README.rst
  currency_rate_inverted/__init__.py
  currency_rate_inverted/__manifest__.py
  currency_rate_inverted/i18n/currency_rate_inverted.pot
  currency_rate_inverted/i18n/fr.po
  currency_rate_inverted/models/__init__.py
  currency_rate_inverted/models/res_currency.py
  currency_rate_inverted/readme/CONFIGURE.rst
  currency_rate_inverted/readme/CONTRIBUTORS.rst
  currency_rate_inverted/readme/DESCRIPTION.rst
  currency_rate_inverted/static/description/icon.png
  currency_rate_inverted/static/description/index.html
  currency_rate_inverted/tests/__init__.py
  currency_rate_inverted/tests/test_currency_rate_inverted.py
  currency_rate_inverted/views/res_currency_view.xml
Labels: approved, needs review, ready to merge

#46 [FIX][11.0] Duplicated view
  currency_monthly_rate/views/res_currency.xml
Labels: approved
