Repository OCA/currency, pull requests merged in 2021-11, with the labels that each got.

#116 [13.0][FIX] currency_rate_update: Add noupdate=1 to cron record.
  currency_rate_update/data/cron.xml
Labels: bot is merging ⏳

#118 [14.0][FIX] currency_rate_update: Add noupdate=1 to cron record.
  currency_rate_update/data/cron.xml
Labels: approved, bot is merging ⏳

#119 [12.0][FIX] currency_rate_update: Add noupdate=1 to cron record.
  currency_rate_update/data/cron.xml
Labels: approved, ready to merge, bot is merging ⏳

#120 [12.0][FIX] currency_rate_update: correct migration script
  currency_rate_update/migrations/12.0.1.1.1/openupgrade_analysis.txt
  currency_rate_update/migrations/12.0.1.1.1/openupgrade_analysis_work.txt
  currency_rate_update/migrations/12.0.1.1.1/pre-migration.py
Labels: approved

#121 [13.0][FIX] currency_rate_update: Set the correct default value in the company_id field (avoid deprecated options).
  currency_rate_update/models/res_currency_rate_provider.py
Labels: bot is merging ⏳

#122 [14.0][FIX] currency_rate_update: Set the correct default value in the company_id field (avoid deprecated options)
  currency_rate_update/models/res_currency_rate_provider.py
Labels: bot is merging ⏳
