Repository OCA/currency, pull requests merged in 2022-12, with the labels that each got.

#144 [UPD] dotfiles
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved

#147 [13.0][IMP] currency_rate_update: Do not call the _schedule_next_run() method if there is no data.
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/models/res_currency_rate_provider_ECB.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, ready to merge, bot is merging ⏳

#149 [14.0][IMP] Updated from template to Github actions
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: approved

#148 [14.0][IMP] currency_rate_update: Do not call the _schedule_next_run() method if there is no data.
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/models/res_currency_rate_provider_ECB.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#150 [15.0][IMP] currency_rate_update: Do not call the _schedule_next_run() method if there is no data.
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/models/res_currency_rate_provider_ECB.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#153 [16.0][IMP] currency_rate_update: Do not call the _schedule_next_run() method if there is no data.
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/models/res_currency_rate_provider_ECB.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#154 [13.0][FIX] currency_rate_update: Fix next_run (Avoid always set with current date)
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#155 [14.0][FIX] currency_rate_update: Fix next_run (Avoid always set with current date)
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#152 [16.0][FIX] currency_rate_update
  currency_rate_update/models/res_currency_rate_provider.py
Labels: approved, bot is merging ⏳

#156 [15.0][FIX] currency_rate_update: Fix next_run (Avoid always set with current date)
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/tests/test_currency_rate_update.py
Labels: approved, bot is merging ⏳

#157 [15.0][FIX] currency_rate_update
  currency_rate_update/models/res_currency_rate_provider.py
Labels: approved, bot is merging ⏳

#158 [14.0][FIX] currency_rate_update
  currency_rate_update/models/res_currency_rate_provider.py
Labels: approved, bot is merging ⏳

#159 [16.0][IMP] currency_rate_update
  currency_rate_update/models/res_currency_rate_provider.py
  currency_rate_update/readme/CONTRIBUTORS.rst
  currency_rate_update/tests/test_currency_rate_update.py
  currency_rate_update/views/res_currency_rate_provider.xml
Labels: approved, bot is merging ⏳
